<script>

</script>

<div class="flex justify-center h-screen">
  <div class="w-1/2">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur leo. Maecenas non diam cursus, imperdiet massa eget, pellentesque ex. Vestibulum lacinia porttitor ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar egestas libero, in sodales mauris efficitur a. Fusce non bibendum dui. Fusce finibus vel arcu non finibus. Pellentesque vehicula elit at orci pharetra, vel posuere libero volutpat. Proin eu tellus non dolor semper efficitur. Proin sodales, magna a varius convallis, dui turpis facilisis ipsum, id tempus metus dui eu leo. Integer lacinia, justo ut facilisis facilisis, risus elit posuere ipsum, at porttitor lacus mauris sed ligula.
    </div>
</div>

<style lang="postcss">

</style>
